export { default as Home } from "./Home";
export { default as Bugs } from "./Bugs";
export { default as Epics } from "./Epics";
export { default as Applications } from "./Applications";
export { default as Create } from "./Create";
export { default as Dashboard } from "./Dashboard";
export { default as Documents } from "./Documents";
export { default as Goals } from "./Goals";
export { default as Spaces } from "./Spaces";
